import React, { useState, useEffect } from 'react';
import { Plus, Search, Edit2, Trash2, X, RefreshCw, Users, Wrench, Package, Truck } from 'lucide-react';

const ResourcePlanning = () => {
  const [resources, setResources] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [showAddModal, setShowAddModal] = useState(false);
  const [editingResource, setEditingResource] = useState(null);
  const [formData, setFormData] = useState({ resource_id: '', name: '', type: 'equipment', location: '', status: 'available', assigned_to: '', notes: '' });

  const types = [{ value: 'equipment', label: 'Equipment', icon: Wrench }, { value: 'vehicle', label: 'Vehicle', icon: Truck }, { value: 'material', label: 'Material', icon: Package }, { value: 'manpower', label: 'Manpower', icon: Users }];
  const statuses = [{ value: 'available', label: 'Available', color: 'bg-green-100 text-green-700' }, { value: 'in_use', label: 'In Use', color: 'bg-blue-100 text-blue-700' }, { value: 'maintenance', label: 'Maintenance', color: 'bg-orange-100 text-orange-700' }, { value: 'unavailable', label: 'Unavailable', color: 'bg-red-100 text-red-700' }];

  useEffect(() => { setTimeout(() => { setResources([{ id: '1', resource_id: 'EQ-001', name: 'Generator 50KVA', type: 'equipment', location: 'Site A', status: 'in_use', assigned_to: 'Project Alpha' }, { id: '2', resource_id: 'VH-001', name: 'Pickup Truck', type: 'vehicle', location: 'Office', status: 'available', assigned_to: '' }, { id: '3', resource_id: 'EQ-002', name: 'Welding Machine', type: 'equipment', location: 'Workshop', status: 'maintenance', assigned_to: '' }]); setLoading(false); }, 500); }, []);

  const handleSubmit = (e) => { e.preventDefault(); if (editingResource) { setResources(resources.map(r => r.id === editingResource.id ? { ...r, ...formData } : r)); } else { setResources([...resources, { ...formData, id: Date.now().toString() }]); } setShowAddModal(false); setEditingResource(null); resetForm(); };
  const handleDelete = (id) => { if (window.confirm('Are you sure?')) setResources(resources.filter(r => r.id !== id)); };
  const resetForm = () => setFormData({ resource_id: '', name: '', type: 'equipment', location: '', status: 'available', assigned_to: '', notes: '' });
  const openEditModal = (resource) => { setEditingResource(resource); setFormData({ ...resource }); setShowAddModal(true); };
  const filteredResources = resources.filter(r => r.name?.toLowerCase().includes(searchTerm.toLowerCase()) || r.resource_id?.toLowerCase().includes(searchTerm.toLowerCase()));
  const getStatusColor = (status) => statuses.find(s => s.value === status)?.color || 'bg-slate-100 text-slate-700';
  const getTypeIcon = (type) => { const t = types.find(ty => ty.value === type); return t ? t.icon : Package; };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">Resource Planning</h1><p className="text-slate-500 mt-1">Manage equipment and resources</p></div><button onClick={() => { resetForm(); setEditingResource(null); setShowAddModal(true); }} className="flex items-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-lg hover:bg-slate-800"><Plus className="w-4 h-4" /> Add Resource</button></div>
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">{statuses.map((s, i) => (<div key={i} className="bg-white rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><span className="text-sm text-slate-600">{s.label}</span><span className={`px-2 py-1 text-xs font-medium rounded-full ${s.color}`}>{resources.filter(r => r.status === s.value).length}</span></div></div>))}</div>
      <div className="flex items-center gap-4"><div className="relative flex-1 max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><input type="text" placeholder="Search resources..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="w-full pl-10 pr-4 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900" /></div><button className="p-2 text-slate-500 hover:bg-slate-100 rounded-lg"><RefreshCw className="w-5 h-5" /></button></div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{loading ? <div className="col-span-full text-center py-8 text-slate-500">Loading...</div> : filteredResources.length === 0 ? <div className="col-span-full text-center py-8 text-slate-500">No resources found</div> : filteredResources.map((resource) => { const TypeIcon = getTypeIcon(resource.type); return (<div key={resource.id} className="bg-white rounded-xl border border-slate-200 p-5 hover:shadow-md transition-shadow"><div className="flex items-start justify-between mb-3"><div className="flex items-center gap-3"><div className="p-2 bg-slate-100 rounded-lg"><TypeIcon className="w-5 h-5 text-slate-600" /></div><div><h3 className="font-semibold text-slate-900">{resource.name}</h3><p className="text-sm text-slate-500">{resource.resource_id}</p></div></div><span className={`px-2 py-1 text-xs font-medium rounded-full ${getStatusColor(resource.status)}`}>{statuses.find(s => s.value === resource.status)?.label}</span></div><div className="space-y-2 text-sm text-slate-600"><p><strong>Type:</strong> {types.find(t => t.value === resource.type)?.label}</p><p><strong>Location:</strong> {resource.location || '-'}</p>{resource.assigned_to && <p><strong>Assigned:</strong> {resource.assigned_to}</p>}</div><div className="mt-4 pt-4 border-t border-slate-100 flex justify-end gap-2"><button onClick={() => openEditModal(resource)} className="p-1.5 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded"><Edit2 className="w-4 h-4" /></button><button onClick={() => handleDelete(resource.id)} className="p-1.5 text-slate-500 hover:text-red-600 hover:bg-red-50 rounded"><Trash2 className="w-4 h-4" /></button></div></div>);})}</div>
      {showAddModal && <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-xl w-full max-w-lg max-h-[90vh] overflow-y-auto"><div className="flex items-center justify-between p-4 border-b border-slate-200"><h3 className="text-lg font-semibold text-slate-900">{editingResource ? 'Edit Resource' : 'Add Resource'}</h3><button onClick={() => setShowAddModal(false)} className="p-1 hover:bg-slate-100 rounded"><X className="w-5 h-5" /></button></div><form onSubmit={handleSubmit} className="p-4 space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-slate-700 mb-1">Resource ID *</label><input type="text" required value={formData.resource_id} onChange={(e) => setFormData({...formData, resource_id: e.target.value})} className="w-full px-3 py-2 border border-slate-200 rounded-lg" /></div><div><label className="block text-sm font-medium text-slate-700 mb-1">Type</label><select value={formData.type} onChange={(e) => setFormData({...formData, type: e.target.value})} className="w-full px-3 py-2 border border-slate-200 rounded-lg">{types.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}</select></div></div><div><label className="block text-sm font-medium text-slate-700 mb-1">Name *</label><input type="text" required value={formData.name} onChange={(e) => setFormData({...formData, name: e.target.value})} className="w-full px-3 py-2 border border-slate-200 rounded-lg" /></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-slate-700 mb-1">Location</label><input type="text" value={formData.location} onChange={(e) => setFormData({...formData, location: e.target.value})} className="w-full px-3 py-2 border border-slate-200 rounded-lg" /></div><div><label className="block text-sm font-medium text-slate-700 mb-1">Status</label><select value={formData.status} onChange={(e) => setFormData({...formData, status: e.target.value})} className="w-full px-3 py-2 border border-slate-200 rounded-lg">{statuses.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}</select></div></div><div><label className="block text-sm font-medium text-slate-700 mb-1">Assigned To</label><input type="text" value={formData.assigned_to} onChange={(e) => setFormData({...formData, assigned_to: e.target.value})} className="w-full px-3 py-2 border border-slate-200 rounded-lg" /></div><div className="flex justify-end gap-3 pt-4 border-t border-slate-200"><button type="button" onClick={() => setShowAddModal(false)} className="px-4 py-2 text-slate-700 bg-slate-100 rounded-lg hover:bg-slate-200">Cancel</button><button type="submit" className="px-4 py-2 bg-slate-900 text-white rounded-lg hover:bg-slate-800">{editingResource ? 'Update' : 'Create'}</button></div></form></div></div>}
    </div>
  );
};

export default ResourcePlanning;
