import React, { useState, useEffect } from 'react';
import { Plus, Search, Edit2, Trash2, X, RefreshCw, PieChart, TrendingUp, AlertCircle } from 'lucide-react';

const BudgetManagement = () => {
  const [budgets, setBudgets] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [showAddModal, setShowAddModal] = useState(false);
  const [editingBudget, setEditingBudget] = useState(null);
  const [formData, setFormData] = useState({ department: '', category: '', period: '', allocated: 0, spent: 0, status: 'active' });

  const departments = ['Projects', 'Accounts', 'Sales', 'Purchase', 'HR', 'Operations', 'Exports', 'Finance'];
  const categories = ['Salaries', 'Operations', 'Marketing', 'Equipment', 'Travel', 'Utilities', 'Miscellaneous'];
  const statuses = [{ value: 'active', label: 'Active', color: 'bg-green-100 text-green-700' }, { value: 'exceeded', label: 'Exceeded', color: 'bg-red-100 text-red-700' }, { value: 'closed', label: 'Closed', color: 'bg-slate-100 text-slate-700' }];

  useEffect(() => { setTimeout(() => { setBudgets([{ id: '1', department: 'Projects', category: 'Operations', period: 'Q1 2025', allocated: 500000, spent: 320000, status: 'active' }, { id: '2', department: 'Sales', category: 'Marketing', period: 'Q1 2025', allocated: 300000, spent: 285000, status: 'active' }, { id: '3', department: 'HR', category: 'Salaries', period: 'Q1 2025', allocated: 1200000, spent: 1250000, status: 'exceeded' }]); setLoading(false); }, 500); }, []);

  const handleSubmit = (e) => { e.preventDefault(); if (editingBudget) { setBudgets(budgets.map(b => b.id === editingBudget.id ? { ...b, ...formData } : b)); } else { setBudgets([...budgets, { ...formData, id: Date.now().toString() }]); } setShowAddModal(false); setEditingBudget(null); resetForm(); };
  const handleDelete = (id) => { if (window.confirm('Are you sure?')) setBudgets(budgets.filter(b => b.id !== id)); };
  const resetForm = () => setFormData({ department: '', category: '', period: '', allocated: 0, spent: 0, status: 'active' });
  const openEditModal = (budget) => { setEditingBudget(budget); setFormData({ ...budget }); setShowAddModal(true); };
  const filteredBudgets = budgets.filter(b => b.department?.toLowerCase().includes(searchTerm.toLowerCase()) || b.category?.toLowerCase().includes(searchTerm.toLowerCase()));
  const getStatusColor = (status) => statuses.find(s => s.value === status)?.color || 'bg-slate-100 text-slate-700';
  const formatCurrency = (amt) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 0 }).format(amt || 0);
  const getUtilization = (spent, allocated) => allocated > 0 ? Math.round((spent / allocated) * 100) : 0;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">Budget Management</h1><p className="text-slate-500 mt-1">Track department budgets</p></div><button onClick={() => { resetForm(); setEditingBudget(null); setShowAddModal(true); }} className="flex items-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-lg hover:bg-slate-800"><Plus className="w-4 h-4" /> Add Budget</button></div>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="bg-white rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-3"><div className="p-2 bg-blue-50 rounded-lg"><PieChart className="w-5 h-5 text-blue-600" /></div><div><p className="text-sm text-slate-500">Total Allocated</p><p className="text-xl font-bold text-slate-900">{formatCurrency(budgets.reduce((sum, b) => sum + b.allocated, 0))}</p></div></div></div><div className="bg-white rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-3"><div className="p-2 bg-green-50 rounded-lg"><TrendingUp className="w-5 h-5 text-green-600" /></div><div><p className="text-sm text-slate-500">Total Spent</p><p className="text-xl font-bold text-slate-900">{formatCurrency(budgets.reduce((sum, b) => sum + b.spent, 0))}</p></div></div></div><div className="bg-white rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-3"><div className="p-2 bg-red-50 rounded-lg"><AlertCircle className="w-5 h-5 text-red-600" /></div><div><p className="text-sm text-slate-500">Exceeded</p><p className="text-xl font-bold text-red-600">{budgets.filter(b => b.status === 'exceeded').length}</p></div></div></div></div>
      <div className="flex items-center gap-4"><div className="relative flex-1 max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><input type="text" placeholder="Search budgets..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="w-full pl-10 pr-4 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900" /></div><button className="p-2 text-slate-500 hover:bg-slate-100 rounded-lg"><RefreshCw className="w-5 h-5" /></button></div>
      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50 border-b border-slate-200"><tr><th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase">Department</th><th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase">Category</th><th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase">Period</th><th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase">Allocated</th><th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase">Spent</th><th className="px-4 py-3 text-center text-xs font-medium text-slate-500 uppercase">Utilization</th><th className="px-4 py-3 text-center text-xs font-medium text-slate-500 uppercase">Status</th><th className="px-4 py-3 text-center text-xs font-medium text-slate-500 uppercase">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan="8" className="px-4 py-8 text-center text-slate-500">Loading...</td></tr> : filteredBudgets.length === 0 ? <tr><td colSpan="8" className="px-4 py-8 text-center text-slate-500">No budgets found</td></tr> : filteredBudgets.map((budget) => { const util = getUtilization(budget.spent, budget.allocated); return (<tr key={budget.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-medium text-slate-900">{budget.department}</td><td className="px-4 py-3 text-sm text-slate-600">{budget.category}</td><td className="px-4 py-3 text-sm text-slate-600">{budget.period}</td><td className="px-4 py-3 text-sm text-right text-slate-900">{formatCurrency(budget.allocated)}</td><td className="px-4 py-3 text-sm text-right text-slate-900">{formatCurrency(budget.spent)}</td><td className="px-4 py-3"><div className="flex items-center gap-2"><div className="flex-1 h-2 bg-slate-100 rounded-full"><div className={`h-full rounded-full ${util > 100 ? 'bg-red-500' : util > 80 ? 'bg-amber-500' : 'bg-green-500'}`} style={{width: `${Math.min(util, 100)}%`}}></div></div><span className="text-xs font-medium">{util}%</span></div></td><td className="px-4 py-3 text-center"><span className={`px-2 py-1 text-xs font-medium rounded-full ${getStatusColor(budget.status)}`}>{statuses.find(s => s.value === budget.status)?.label}</span></td><td className="px-4 py-3"><div className="flex items-center justify-center gap-2"><button onClick={() => openEditModal(budget)} className="p-1.5 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded"><Edit2 className="w-4 h-4" /></button><button onClick={() => handleDelete(budget.id)} className="p-1.5 text-slate-500 hover:text-red-600 hover:bg-red-50 rounded"><Trash2 className="w-4 h-4" /></button></div></td></tr>);})}</tbody></table></div></div>
      {showAddModal && <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-xl w-full max-w-lg"><div className="flex items-center justify-between p-4 border-b border-slate-200"><h3 className="text-lg font-semibold text-slate-900">{editingBudget ? 'Edit Budget' : 'Add Budget'}</h3><button onClick={() => setShowAddModal(false)} className="p-1 hover:bg-slate-100 rounded"><X className="w-5 h-5" /></button></div><form onSubmit={handleSubmit} className="p-4 space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-slate-700 mb-1">Department</label><select value={formData.department} onChange={(e) => setFormData({...formData, department: e.target.value})} className="w-full px-3 py-2 border border-slate-200 rounded-lg">{departments.map(d => <option key={d} value={d}>{d}</option>)}</select></div><div><label className="block text-sm font-medium text-slate-700 mb-1">Category</label><select value={formData.category} onChange={(e) => setFormData({...formData, category: e.target.value})} className="w-full px-3 py-2 border border-slate-200 rounded-lg">{categories.map(c => <option key={c} value={c}>{c}</option>)}</select></div></div><div><label className="block text-sm font-medium text-slate-700 mb-1">Period</label><input type="text" placeholder="e.g., Q1 2025" value={formData.period} onChange={(e) => setFormData({...formData, period: e.target.value})} className="w-full px-3 py-2 border border-slate-200 rounded-lg" /></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-slate-700 mb-1">Allocated Amount</label><input type="number" value={formData.allocated} onChange={(e) => setFormData({...formData, allocated: parseFloat(e.target.value) || 0})} className="w-full px-3 py-2 border border-slate-200 rounded-lg" /></div><div><label className="block text-sm font-medium text-slate-700 mb-1">Spent Amount</label><input type="number" value={formData.spent} onChange={(e) => setFormData({...formData, spent: parseFloat(e.target.value) || 0})} className="w-full px-3 py-2 border border-slate-200 rounded-lg" /></div></div><div className="flex justify-end gap-3 pt-4 border-t border-slate-200"><button type="button" onClick={() => setShowAddModal(false)} className="px-4 py-2 text-slate-700 bg-slate-100 rounded-lg hover:bg-slate-200">Cancel</button><button type="submit" className="px-4 py-2 bg-slate-900 text-white rounded-lg hover:bg-slate-800">{editingBudget ? 'Update' : 'Create'}</button></div></form></div></div>}
    </div>
  );
};

export default BudgetManagement;
